image: registry.gitlab.freifunk-stuttgart.de/firmware/ffs-buildenv:master

variables:
  GIT_SUBMODULE_STRATEGY: normal
  DOCKER_DRIVER: overlay2

stages:
  - build

.target:
  stage: build
  script:
    - make -C gluon update GLUON_SITEDIR="$CI_PROJECT_DIR"
    - make -C gluon GLUON_SITEDIR="$CI_PROJECT_DIR" GLUON_TARGET="$GLUON_TARGET" GLUON_BRANCH=stable V=1 -j`nproc`
  artifacts: 
    paths:
      - gluon/output/
    expire_in: 1 day
  cache:
    paths:
      - gluon/openwrt/dl
      - gluon/openwrt/staging_dir
      - gluon/openwrt/feeds
    key: "target-$GLUON_TARGET"
 
target:ramips-mt7620:
  extends: .target
  variables:
    GLUON_TARGET: ramips-mt7620
